# Site settings
title: A roadmap to Web Development
header-img: img/home-bg.png
email: ritchey0713@gmail.com
copyright_name: ritchey0713
description: > # this means to ignore newlines until "baseurl:"
  My greatest adventure, my quest as a Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ritchey0713
learn_profile: ritchey0713
email_username: ritchey0713@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
